config/routes.rb
Recipes::Application.routes.draw do
  get "password_resets/new"

  root :to => 'users#index'
  get "sessions/new"
  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  match '/auth/:provider/callback', :to => 'sessions#omni'
  match '/auth/failure', :to => 'sessions#failure'
  post '/users/activate' => 'users#activate'
  resources :password_resets, :only => [:new, :edit, :update, :create]
  resources :users do
    member do
      get 'recipes'
      get 'faved_recipes'
      post 'update_password'
      match '/:activation_id/activate' => 'users#new_user_activate', :as => 'activate'
      post '/generate_activation' => 'users#profile_activate', :as => 'generate_activate'
    end
    resources :recipes do
      match '/fav' => 'users#favorite'
    end
  end
  resources :sessions
  resources :ingredients do
    member do
      get 'recipes'
    end
  end
  
  resources :recipes do
    match '/fav' => 'recipes#favorite'
  end

  scope '/search' do
    match '/' => 'search#index'
    match '/recipes' => 'search#recipes'
  end

  scope '/recipes' do
    match '/:name' => 'recipes#show'
    match '/:id/update_rating', :controller => 'recipes', :action => 'update_rating'
    match '/new/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
    match '/:id/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
  end

  scope '/user' do
    match '/' => 'users#me'
    match '/invite' => 'users#invite'
  end
  #match '/recipes/:name', :controller => 'recipes', :action => 'show'
  match '/ingredients/:name' => 'ingredients#show'
  
  #match '/:email', :controller => 'users', :action => 'edit'
  match '/me' => 'users#me'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :amounts
  has_many :ingredients, :through => :amounts

  has_many :personalRecipeInfo, :dependent => :destroy
  has_many :users, :through => :personalRecipeInfo

  acts_as_indexed :fields => [:name, :desc]

  mount_uploader :image, RecipePictureUploader

  validates_presence_of :name
  validates_length_of :name, :minimum => 3
  validates_uniqueness_of :url_slug
  validates_inclusion_of :difficulty, :in => %w(Beginner Moderate Difficult Expert)
  validates_presence_of :cook_time
  validates_presence_of :desc
  validates_length_of :desc, :minimum => 100
  
  def to_param
    url_slug
  end

=begin LEGACY
  def ingredients_attributes=(params)
    params.each_with_index do |(key, value), index|
      if existing_ingredient = Ingredient.find_by_name(value['name'])
        self.ingredients << existing_ingredient unless self.ingredients.include? existing_ingredient
        @details = self.amounts.where('ingredient_id = ' + existing_ingredient.id.to_s).first
        logger.info self.amounts.inspect
        @details['amount'] = value['amount'].to_i
        @details['units'] = value['units'] unless value['units'] == nil
        @details.save
      else
        if value['name'].empty?
          break
        end
        slug = value['name'].downcase
        ingredient = Ingredient.new({"name" => slug.gsub(/\b\w/){$&.upcase}, "url_slug" => slug.gsub(/\s/,'-')})
        ingredient.save
        self.ingredients << ingredient
      end
    end
  end
=end
end

app/controllers/recipes_controller.rb
 require 'mathn'
 class RecipesController < ApplicationController
  layout 'recipes'
  helper_method :sort_type, :sort_direction
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.includes(:ingredients).order(sort_type + " " + sort_direction).page(params[:page]).per(9)
    @activeSort = sort_type
    respond_to do |format|
      format.html { render :layout => 'wall'}
      format.json { render json: @recipes }
      format.js
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @page = true
    @recipe = Recipe.includes(:ingredients, :personalRecipeInfo, :users).find_by_url_slug(params[:id])    
    if @recipe.nil?
      @recipe = Recipe.includes(:ingredients, :personalRecipeInfo, :users).find_by_url_slug(params[:name])
    end
    @ingredients = []
    @recipe.amounts.each do |amount|
      temp = {}
      temp['ingredient'] = @recipe.ingredients.select{|i| i.id == amount.ingredient_id}.first
      temp['amount'] = amount.amount
      temp['units'] = amount.units
      temp['details'] = amount.details
      @ingredients << temp
    end

    @cook_time = hash_from_cook_time_string(@recipe.cook_time)
    @created_by = @recipe.users.first
    @created_by_name = name_to_use(@created_by)[0]

    if current_user
      @usersRecipeInfo = @recipe.personalRecipeInfo.select{|info| info.user_id == current_user.id}.first
      if @usersRecipeInfo
        if @usersRecipeInfo.favorite == true
          @favorite = true
        else
          @favorite = false
        end
        if @usersRecipeInfo.rating
          @personal_rating = @usersRecipeInfo.rating
        else
          @personal_rating = nil
        end
      else
        @favorite = false
        @personal_rating = nil
      end
      if session[:recent_recipes] and session[:recent_recipes].index(@recipe.id) == nil
        if session[:recent_recipes].count > 3
          session[:recent_recipes].shift
        end
        session[:recent_recipes].push(@recipe.id)
      end
    end

    @users = @recipe.users
    @forks = @recipe.favorites
    #is this my recipe?
    @myRecipe = true if @recipe.users.first == current_user

    respond_to do |format|
      format.html
      format.json { render json: @recipe }
      format.js
    end
  end

  def search
    @recipes = Recipe.order('name ASC')
    render :action => 'show'
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
    @availableIngredients = Ingredient.order('name ASC')
    respond_to do |format|
      if current_user
        format.html # new.html.erb
        format.json { render json: @recipe }
      else
        format.html { redirect_to recipes_url, notice: 'You must be logged in to create a recipe!'}
      end
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.includes(:ingredients).find_by_url_slug(params[:id])
    amounts = @recipe.amounts
    @ingredients = []
    @cook_time = hash_from_cook_time_string(@recipe.cook_time)
    amounts.each do |amount|
      temp = {}
      temp['name'] = @recipe.ingredients.select{|i| i.id == amount.ingredient_id}.first.name
      temp['amount'] = amount.amount
      temp['units'] = amount.units
      temp['details'] = amount.details
      @ingredients << temp
    end
    @availableIngredients = Ingredient.order('name ASC')
  end

  # POST /recipes
  # POST /recipes.json
  def create
    params[:recipe]['url_slug'] = get_slug(params[:recipe]['name'])
    params[:recipe]['created_by'] = current_user.id
    params[:recipe]['cook_time'] = "#{params[:cook_time][0]}d#{params[:cook_time][1]}h#{params[:cook_time][2]}m"
    @recipe = Recipe.new(params[:recipe])
    @ingredients = params[:ingredients]
    @ingredients.delete_if {|i| i['name'].blank? or i['amount'].blank?}
    if @ingredients.empty?
      logger.info @ingredients.inspect
      @recipe.errors[:base] << 'You must add some ingredients!'
    end
    @ingredients.each do |i|
      if i['name'].empty?
        break
      end
      formatted_name = i['name'].gsub(/\b\w/){$&.upcase}
      ingredient = Ingredient.find_by_name(formatted_name)
      if ingredient.nil?
        ingredient = Ingredient.new({"name" => formatted_name, 'url_slug' => get_slug(i['name'])})
      end
      if !@recipe.ingredients.include?(ingredient)
        @recipe.ingredients << ingredient
      end
    end
    @recipe.users << current_user
    respond_to do |format|
      if @recipe.errors.any?
        format.html {render action: 'new'}
        format.json {render json: @recipe.errors}
      else
        if @recipe.save
          add_amounts(@recipe, @ingredients)
          format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
          format.json { render json: @recipe, status: :created, location: @recipe }
        else
          format.html { render action: 'new' }
          format.json { render json: @recipe.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.includes(:ingredients).find_by_url_slug(params[:id])
    @ingredients = params[:ingredients]
    logger.debug @ingredients
    @ingredients.each do |i|
      if i['name'].empty?
        break
      end
      formatted_name = i['name'].gsub(/\b\w/){$&.upcase}
      ingredient = Ingredient.find_by_name(formatted_name)
      if ingredient.nil?
        ingredient = Ingredient.new({"name" => formatted_name, 'url_slug' => get_slug(i['name'])})
      end
      if !@recipe.ingredients.include?(ingredient)
        @recipe.ingredients << ingredient
      end
    end
    logger.debug params[:cook_time]
    params[:recipe]['url_slug'] = get_slug(params[:recipe]['name'])
    params[:recipe]['cook_time'] = "#{params[:cook_time][0]}d#{params[:cook_time][1]}h#{params[:cook_time][2]}m"
    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        add_amounts(@recipe, @ingredients)
        format.html { redirect_to @recipe }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipes = Recipe.all
    respond_to do |format|
      format.html {redirect_to recipes_url, :status => 401}
      format.json {redirect_to recipes_url, :status => 401}
    end
  end

  # POST /recipes/:id/update_rating
  def update_rating
    @recipe = Recipe.includes(:users).find_by_url_slug(params[:id])
    @personal_rating = PersonalRecipeInfo.find_by_user_id_and_recipe_id(current_user.id, @recipe.id)
    if @personal_rating.nil?
      @recipe.users << current_user
      if @recipe.save
        #do nothing
      else
        redirect_to recipes_url, :notice => 'Something went wrong.'
      end
    end
    @personal_rating.rating = Integer(params[:rating])
    respond_to do |format|
      if @personal_rating.save
        @recipe.rating = @recipe.personalRecipeInfo.average(:rating)
        @recipe.total_ratings = @recipe.personalRecipeInfo.where("rating IS NOT NULL").count
        if @recipe.save
          format.json {render json: @recipe}
          format.xml {render xml: @recipe}
        else
          format.json {render json: @recipe.errors, status: :unprocessable_entity}
          format.xml {render xml: @recipe.errors}
        end
      else
        format.json {render json: @recipe.errors, status: :unprocessable_entity}
        format.xml {render xml: @recipe.errors}
      end
    end
  end

  def favorite
    recipe = Recipe.find_by_url_slug(params[:recipe_id])
    user = current_user
    render :json => recipe
  end

  def render_ingredients_input
    respond_to do |format|
      format.js {render 'index.js'}
    end
  end

  def get_slug(name)
    return name.downcase.gsub(/\s/,'-')
  end

  private

  def sort_type
    Recipe.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def name_to_use(user)
    if user.display_name
      return [user.display_name, user.display_name]
    elsif user.name
      return [user.name, user.name.split(' ')[0]]
    else
      return [user.email, user.email]
    end
  end

  def add_amounts(recipe, amounts)
    recipe.ingredients.each_with_index do |ingredient, index|
      amount = recipe.amounts.find_by_ingredient_id(ingredient.id)
      if amounts[index]['amount'].scan('.').length != 0
        amount.amount = amounts[index]['amount'].to_f.round(3)
      elsif amounts[index]['amount'].scan('/').length != 0
        amount.amount = frac_to_float(amounts[index]['amount'])
      else
        amount.amount = amounts[index]['amount']
      end
      amount.units = (amounts[index]['units'].nil? or amounts[index]['units'].blank?) ? '' : amounts[index]['units']
      amount.details = (amounts[index]['details'].nil? or amounts[index]['details'].blank?) ? '' : amounts[index]['details']
      amount.save
    end
  end

  def hash_from_cook_time_string(cook_string = '')
    if cook_string.nil? or cook_string.blank?
      return {'d' => '', 'h' => '', 'm' => ''}
    else
    times = cook_string.split(/\D/)
    return {'d' => times[0], 'h' => times[1], 'm' => times[2]}
    end
  end

  def frac_to_float(fraction)
  number1, number2 = fraction.split(/\s/)
  if number2.nil?
    numerator, denominator = number1.split('/').map(&:to_f)
    denominator ||= 1
    return numerator/denominator
  else
    numerator, denominator = number2.split('/').map(&:to_f)
    denominator ||= 1
    return number1.to_f + (numerator/denominator)
  end
end

  def float_to_frac(floatAmount)
    return Rational(floatAmount, 1)
  end
end

app/helpers/recipes_helper.rb
require 'mathn'

module RecipesHelper
  def convertToHtml(toConvert)
    '<p>'+toConvert.gsub(/(\r\n)+/ ,'</p><p>') + '</p>'
  end

  def formatted_cook_time_string(cook_string)
    if cook_string.nil?
      return ''
    else
      times = cook_string.split(/\D/)
      return [pluralize(times[0], 'day'), pluralize(times[1], 'hour'), pluralize(times[2], 'minute')].join(', ')
    end
  end

  def formatIngredient(ingredient)
    formattedIngredient = ''
    name = ingredient['ingredient'].name
    amount = ingredient['amount']
    fraction = ((amount.remainder(1) != 0) ? float_to_frac(amount, 'hash') : amount.to_i.to_s) unless amount.nil?
    units = (is_plural?(ingredient['units']) ? ingredient['units'].singularize : ingredient['units']) unless (ingredient['units'].nil? or ingredient['units'].blank?)
    details = ingredient['details']
    noOf = ['whole']
    logger.debug units.nil?
    if !amount.nil? and !amount.blank?
      if units.nil? or units.blank?
        if amount > 1
          formattedIngredient = "#{fraction} #{link_to(name.pluralize, ingredient['ingredient'])}"
        else
          formattedIngredient = "#{fraction} #{link_to(name, ingredient['ingredient'])}"
        end
      elsif noOf.include?(units)
        formattedIngredient = "#{pluralize(fraction, units)} #{link_to(name, ingredient['ingredient'])}"
      else
        if (amount.remainder(1) != 0)
          formattedIngredient = "<sup>#{fraction['numerator']}</sup>&frasl;<sub>#{fraction['denominator']}</sub> #{units} of #{link_to(name, ingredient['ingredient'])}"
          if fraction['whole']
            formattedIngredient = "#{fraction['whole']}#{formattedIngredient}"
          end
        else
          formattedIngredient = "#{pluralize(fraction, units)} of #{link_to(name, ingredient['ingredient'])}"
        end
      end
      if !details.nil? and !details.blank?
        formattedIngredient += ", #{details}"
      end
    else
      formattedIngredient = "#{link_to(name, ingredient['ingredient'])}"
    end
    return formattedIngredient
  end

  def frac_to_float(fraction)
    number1, number2 = fraction.split(/\s/)
    if number2.nil?
      numerator, denominator = number1.split('/').map(&:to_f)
      denominator ||= 1
      return numerator/denominator
    else
      numerator, denominator = number2.split('/').map(&:to_f)
      denominator ||= 1
      return number1.to_f + (numerator/denominator)
    end
  end

  def float_to_frac(floatAmount, type = 'string')
    if type == 'array'
      return Rational(floatAmount, 1).to_s.split('/')
    else
      floatArray = Rational(floatAmount, 1).to_s.split('/').map(&:to_i)
      if floatArray[1].nil?
        returnHash = Hash['whole' => floatArray[0]]
      elsif (floatArray[0]/floatArray[1]).to_i > 0
        wholePart = (floatArray[0]/floatArray[1]).to_i
        returnHash = Hash["whole" => wholePart, "numerator" => floatArray[0] - (floatArray[1] * wholePart), "denominator" => floatArray[1]]
      else
        returnHash = Hash["numerator" => floatArray[0], "denominator" => floatArray[1]]
      end
      if type == 'hash'
        return returnHash.each{|k,v| returnHash[k] = v.to_s}
      else
        returnHash.each{|k,v| v.to_s}
        if returnHash.include?('numerator') && returnHash.include?('denominator')
          returnString = "#{returnHash['numerator']}/#{returnHash['denominator']}"
          if returnHash['whole']
            returnString = "#{returnHash['whole']} #{returnString}"
          end
        else
          returnString = "#{returnHash['whole']}"
        end
        return returnString
      end
    end
  end

  def is_plural?(string)
    string.pluralize == string && string.singularize != string
  end
end

app/views/recipes/_edit_form.html.haml
= form_for(@recipe) do |f|
  - if @recipe.errors.any?
    %div#error_explaination
      %h2= pluralize(@recipe.errors.count, 'error') 
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg
  %div.inner.left_page
    %div.pencil
    %div.image_field
      = @recipe.image? ? image_tag(@recipe.image_url, {:class => ['preview_image', 'detail_pic'] , :size => '300x225'}) : image_tag('default.png', :size => '300x225', :class => ['default_pic', 'detail_pic'])
      %div.tape.left-tape.bottom-tape
      %div.tape.left-tape.top-tape
      = f.file_field :image, :class => 'recipe_image_upload'
    %div.field
      %div.input_wrap
        = f.label :name, "Name:"
        = f.text_field :name
    %div.field
      %div.input_wrap
        = f.label :difficulty, "Difficultly:"
        = f.select(:difficulty, ['Beginner', 'Moderate', 'Difficult', 'Expert'])
    %div.field
      %div.input_wrap
        = f.label :serving_size, "Serving Size:"
        = f.select(:serving_from, [1,2,3,4,5,6,7,8,9,"10+"])
        to
        = f.select(:serving_to, ["",2,3,4,5,6,7,8,9,"10+"])
    %div.field
      %div.input_wrap.cook_time_value 
        Cook Time:
        %span.days 0
        %span.day_label days,
        = hidden_field_tag 'cook_time[]', @cook_time['d'], :class => 'hidden_days'
        %span.hours 0
        %span.hour_label hours,
        = hidden_field_tag 'cook_time[]', @cook_time['h'], :class => 'hidden_hours'
        %span.minutes 0
        %span.minute_label minutes
        = hidden_field_tag 'cook_time[]', @cook_time['m'], :class => 'hidden_minutes'
      %div.slider_wrap
        %div.slider{:data => {:cook_time => @recipe.cook_time}}
  %div.inner.right_page.edit_page
    %h1
      = "Editing #{@recipe.name}"
    %div.right_page_inner
      %div.edit_ingredients
        %a.add_new_ingredient{:href => '#'}Add another ingredient
        - @ingredients.each do |ingredient|
          %div.ingredient
            = text_field_tag :name, ingredient['name'], {:name => 'ingredients[][name]', :class => 'ingredients-input', :placeholder => 'Enter ingredient name'}
            = text_field_tag :amount, (ingredient['amount'].nil? ? nil : float_to_frac(ingredient['amount'])), {:name => 'ingredients[][amount]', :class => 'ingredients-amount', :placeholder => 'Amount'}
            = text_field_tag :units, (ingredient['units'].nil? ? nil : ingredient['units']), {:name => 'ingredients[][units]', :class => 'ingredients-units', :placeholder => 'Units' }
            =text_field_tag :details, (ingredient['details'].nil? ? nil : ingredient['details']), {:placeholder => 'Details', :name => 'ingredients[][details]', :class => 'ingredients-details'}
      %div.prepartation
        = f.label :desc, "Preparation Instructions:"
        = f.text_area :desc, :rows => 10

      %div.actions
        = f.submit :class => 'pretty_button'

app/views/recipes/_form.html.haml
= form_for(@recipe) do |f|
  - if @recipe.errors.any?
    %div#error_explaination
      %h2= pluralize(@recipe.errors.count, 'error') 
      %ul
        - @recipe.errors.full_messages.each do |msg|
          %li= msg
  %div.inner.left_page
    %div.image_field
      - if @recipe.image?
        = image_tag(@recipe.image_url, {:class => ['preview_image', 'detail_pic'] , :size => '300x225'})
      - else
        %div.empty_image
      %div.tape.left-tape.bottom-tape
      %div.tape.left-tape.top-tape
      = f.file_field :image, :class => 'recipe_image_upload'
    %div.field
      %div.input_wrap
        = f.label :name, "Name:"
        = f.text_field :name
    %div.field
      %div.input_wrap
        = f.label :difficulty, "Difficultly:"
        = f.select(:difficulty, ['Beginner', 'Moderate', 'Difficult', 'Expert'])
    %div.field
      %div.input_wrap
        = f.label :serving_size, "Serving Size:"
        = f.select(:serving_from, [1,2,3,4,5,6,7,8,9,"10+"])
        to
        = f.select(:serving_to, ["",2,3,4,5,6,7,8,9,"10+"])
    %div.field
      %div.input_wrap.cook_time_value 
        Cook Time:
        %span.days 0
        %span.day_label days,
        = hidden_field_tag 'cook_time[]', "0", :class => 'hidden_days'
        %span.hours 0
        %span.hour_label hours,
        = hidden_field_tag 'cook_time[]', "0", :class => 'hidden_hours'
        %span.minutes 0
        %span.minute_label minutes
        = hidden_field_tag 'cook_time[]', "0", :class => 'hidden_minutes'
      %div.slider_wrap
        %div.slider{:data => {:cook_time => @recipe.cook_time}}
  %div.inner.right_page.edit_page
    %h1 New Recipe
    %div.right_page_inner
      %div.new_ingredients
        Ingredients:
        %a.add_new_ingredient.right{:href => '#'}Add another ingredient
        %div.ingredient_list
          %div.ingredient.example
            %label.name{:for => 'ingredients[][name]'}
              Name
            %label.amount
              Amount
            %label.units
              Units
            %label.details
              Details 
              %span{:style => 'font-size: 0.85em'}
                (ex: chopped)
          %div.ingredient
            =text_field_tag :name, nil, {:placeholder => 'Name', :name => 'ingredients[][name]', :class => 'ingredients-input'}
            =text_field_tag :amount, nil, {:placeholder => 'Amount', :name => "ingredients[][amount]", :class => 'ingredients-amount'}
            =text_field_tag :units, nil, {:placeholder => 'Units', :name => "ingredients[][units]", :class => 'ingredients-units'}
            =text_field_tag 'details', nil, {:placeholder => 'Details', :name => 'ingredients[][details]', :class => 'ingredients-details'}
      %div.prepartation
        = f.label :desc, "Preparation Instructions:"
        = f.text_area :desc, :rows => 10, :placeholder => 'How do you make it?'

      %div.actions
        = f.submit 'Create recipe', {:class => 'pretty_button save'}
        /= f.button('Cancel', {:type => 'button'})

app/views/recipes/_ingredient_input.html.haml
%input{:type => 'text', :name => 'ingredients[]'}

app/views/recipes/_recipe.html.haml
%div{:class => "recipe_list #{type}_list"}
  %div.recipe_picture{:id => "#{recipe.name}"}
    - if recipe.image?
      = link_to image_tag(recipe.image_url(:thumb)), recipe
    - else
      = link_to image_tag('default.png', :size => '200x200'), recipe
    %div.recipe_bottom
      %div.recipe_link
        = link_to recipe.name, recipe
      %div.right
        = pluralize(recipe.favorites, 'fork')
  %div.clearfix

app/views/recipes/_recipe_desc.html.haml
%h2 Prepartation:
%div.recipe_desc
  %p
    = @recipe.desc

app/views/recipes/edit.html.haml
/= content_for :add_javascripts do
/  = javascript_include_tag 'recipe_rating'
= render 'edit_form'

app/views/recipes/index.html.haml
= content_for :add_javascripts do
  = javascript_include_tag 'infinite_recipes'
%div.recipe_index_header.show_header
  = link_to 'New Recipe', new_recipe_path, :class => 'pretty_button add' if current_user and current_user.is_activated?
  %div.left
    %h1 All Recipes
    = form_tag '../search/recipes', :method => 'get' do
      = text_field_tag :q, "", :placeholder => 'Search recipes'
      = submit_tag 'Search', :class => 'pretty_button inline'
  %div.right
    %div.sorter
      = sortable 'name'
      = sortable 'created_at', 'Date'
      = sortable 'favorites', 'Forks'
  %div.clearfix
= render :partial => 'recipes_new_overlay', :locals => {:recipes => @recipes, :type => 'recipe_new_index'}

app/views/recipes/index.js.erb
<% if @recipes.count > 0 %>
$('.wall_wrap').append("<%= escape_javascript(render :partial => 'recipes_new_overlay', :locals => {:recipes => @recipes, :type => 'recipe_new_index'})%>")
<% else %>
return null
<% end %>

app/views/recipes/show.html.haml
/= content_for :add_javascripts do
/  = javascript_include_tag 'recipe_rating'
%div.inner.left_page.recipe_show
  %div.first_page
    %div.recipe_image
      = @recipe.image? ? image_tag(@recipe.image_url, :size => '300x225', :class => 'detail_pic') : image_tag('default.png', :size => '300x225', :class => 'detail_pic')
      %div.tape.left-tape.bottom-tape
      %div.tape.left-tape.top-tape
      %div.recipe_details
    %div.recipe_header
      %h2 Details:
      - if current_user and @myRecipe
        = link_to 'Edit', edit_recipe_path(@recipe), :class => 'pretty_button edit inline'
    %p
      Created by:
      = link_to @created_by_name, user_recipes_url(@created_by.id)
    - if !@recipe.serving_from.nil?
      %p.serving_size
        = "Serves #{@recipe.serving_from}"
        - if !@recipe.serving_to.nil?
          = " to #{@recipe.serving_to}"
    %p.rating
      Rating:
      - if @recipe.total_ratings == 0
        No ratings yet! 
      - else
        = @recipe.rating.round(2)
      - if current_user
        %p
          %a.recipe_rating{href:'#', recipe:"#{@recipe.url_slug}"}1
          %a.recipe_rating{href:'#', recipe:"#{@recipe.url_slug}"}2
          %a.recipe_rating{href:'#', recipe:"#{@recipe.url_slug}"}3
          %a.recipe_rating{href:'#', recipe:"#{@recipe.url_slug}"}4
          %a.recipe_rating{href:'#', recipe:"#{@recipe.url_slug}"}5
        %p.personal_rating
          %b< 
            Your rating:
          - if !@personal_rating.nil?
            = @personal_rating
          - else
            You haven't rated this recipe yet!
      - if @cook_time
        %p.cook_time
          Cook time: 
          = formatted_cook_time_string(@recipe.cook_time)
  %div.second_page
    %h1 Preparation:
    %div.recipe_desc
      != convertToHtml(@recipe.desc)
    %div.turn_recipe_back.turn_recipe
      %a{:href=>'#'}back
  %div.clearfix
%div.inner.right_page.show_page
  - if current_user
    - if !@favorite
      %div.bookmark
        = link_to 'Fork it!', user_recipe_fav_url(current_user, @recipe), :method => :post, :remote => true, :dataType => 'text', :class => 'forkit_link'
    - else
      %div.bookmark.forked
        = link_to 'Forked!', user_recipe_fav_url(current_user, @recipe), :method => :post, :remote => true, :dataType => 'text', :class => 'forkit_link'
  %div.first_page
    %h1
      = @recipe.name.titleize
    %div.recipe_info.right_page_inner
      %h2 Ingredients:
      %div.ingredients
        %ul.ingredient_list
          - @ingredients.each do |ingredient|
            %p.ingredient
              != formatIngredient(ingredient)
    %p
      Turn the page for cooking instructions!
  %div.second_page
    %div.recipe_desc
  %div.clearfix
%div.turn_recipe_page.turn_recipe
  %a{:href=>'#'}turn