config/routes.rb
Recipes::Application.routes.draw do
  get "password_resets/new"

  root :to => 'users#index'
  get "sessions/new"
  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  match '/auth/:provider/callback', :to => 'sessions#omni'
  match '/auth/failure', :to => 'sessions#failure'
  post '/users/activate' => 'users#activate'
  resources :password_resets, :only => [:new, :edit, :update, :create]
  resources :users do
    member do
      get 'recipes'
      get 'faved_recipes'
      post 'update_password'
      match '/:activation_id/activate' => 'users#new_user_activate', :as => 'activate'
      post '/generate_activation' => 'users#profile_activate', :as => 'generate_activate'
    end
    resources :recipes do
      match '/fav' => 'users#favorite'
    end
  end
  resources :sessions
  resources :ingredients do
    member do
      get 'recipes'
    end
  end
  
  resources :recipes do
    match '/fav' => 'recipes#favorite'
  end

  scope '/search' do
    match '/' => 'search#index'
    match '/recipes' => 'search#recipes'
  end

  scope '/recipes' do
    match '/:name' => 'recipes#show'
    match '/:id/update_rating', :controller => 'recipes', :action => 'update_rating'
    match '/new/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
    match '/:id/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
  end

  scope '/user' do
    match '/' => 'users#me'
    match '/invite' => 'users#invite'
  end
  #match '/recipes/:name', :controller => 'recipes', :action => 'show'
  match '/ingredients/:name' => 'ingredients#show'
  
  #match '/:email', :controller => 'users', :action => 'edit'
  match '/me' => 'users#me'
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :personalRecipeInfo
  has_many :recipes, :through => :personalRecipeInfo
  #has_many :settings
  has_one :token, :foreign_key => 'user_id', :class_name => 'Token'
  has_many :authorizations
  attr_accessible :name, :display_name, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_length_of :password, :minimum => 5, :on => :create
  validates_confirmation_of :password, :on => :create
  validates_presence_of :password, :on => :create
  validates_presence_of :name, :on => :create
  validates_presence_of :email, :on => :create
  validates_uniqueness_of :email, :on => :create
  validates_format_of :email, 
    :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i, 
    :on => :create

  def self.authenticate(login, password)
    user = find_by_email(login)
    if user and user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def generate_token
    SecureRandom.urlsafe_base64
  end

  def is_activated?
    return self.is_activated
  end
end

app/controllers/users_controller.rb
require 'net/http'
require 'uri'
require 'digest/md5'
require 'json'

class UsersController < ApplicationController
  before_filter :is_logged_in?, :only => [:new]
  layout 'users'

  def index
    @page = false;
    if current_user
      @user = current_user
      @firstName = name_to_use(@user)[1]
      puts session[:recent_recipes].inspect
      if session[:recent_recipes]
        r_view_recipes = Recipe.find(session[:recent_recipes])
        @recentlyViewed = session[:recent_recipes].map{|id| r_view_recipes.detect{|each| each.id == id}}.reverse[0..3]
      end
    else
      @newestRecipes = Recipe.limit(4)
    end
  end

  def new
    @page = false
    @user = User.new
  end

  def me
    @user = current_user
    @avatarUrl = get_avatar_url(@user)
    @recentFav = @user.recipes.where("personal_recipe_infos.favorite IS TRUE").limit(1).first
    @recentCreated = @user.recipes.where(:created_by => @user.id).limit(1).first
    names = name_to_use(@user)
    @name = names[0]
    @first = names[1]

    render 'show'
  end

  def show
    @page = false;
    begin
      @user = User.includes(:recipes => [:ingredients]).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
      return
    end
    @avatarUrl = get_avatar_url(@user)
    if current_user && current_user == @user
      @name = current_user.display_name
      @first = 'You'
      @possessive = 'Your'
    else
      names = name_to_use(@user)
      @name = names[0]
      @first = names[1]
      @possessive = @first + "'s"
    end
    @allIngredients = []
    @user.recipes.each{|r| r.ingredients.each{|i| @allIngredients.push(i)} }
    favorites = get_faves(@user)
    created = @user.recipes.select{|r| r.created_by == @user.id}
    @recentFav = favorites.first
    @recentCreated = created.first
    @totalFav = favorites.count
    @totalCreated = created.count
    respond_to do |format|
      format.html
      format.json {render :partial => 'users/show.json'}
    end
  end

  def not_found
    #user not found function
  end

  def edit
    @page = false
    @user = current_user
    logger.debug current_user
    @passwordChange = Authorization.find_by_user_id_and_provider(@user.id, 'facebook') == nil ? true : false 
  end

  def update
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user == User.authenticate(@user.email, params['old_password'])
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html {redirect_to root_url, :notice => 'Successfully updated!'}
          format.json {head :no_content}
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity}
        end
      end
    end
  end

  def new_user_activate
    token = Token.find_by_active_token(params[:activation_id])
    if token
      if token.user.update_attributes(:is_activated => true)
        redirect_to root_url, :notice => 'Successfully activated your account!'
      else
        redirect_to root_url, :notice => 'Something went wrong with activation. Try again later.'
      end
    else
      redirect_to root_url, :notice => 'Invalid activation id.'
    end
  end

  def profile_activate
    @user = current_user
    if @user
      if @user.token
        @user.token.active_token = @user.generate_token
        if !@user.token.save
          redirect_to root_url, :notice => 'Something went wrong with activation. Try again later.'
        end
      else
        @user.create_token(:active_token => @user.generate_token)
      end
      @user.token.send_activation_email
      redirect_to root_url, :notice => "Activation e-mail sent to #{@user.email}"
    else
      redirect_to current_user, :notice => 'You don\'t have access to this page.'
    end
  end

  def create
    params[:user]['display_name'] = params[:user]['name']
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      if @user.token
        @user.token.active_token = @user.generate_token
        if !@user.token.save
          redirect_to root_url, :notice => 'Activation token could not be saved. Go to profile page to activate your account.'
        end
      else
        @user.create_token(:active_token => @user.generate_token)
      end
      @user.token.send_activation_email
      redirect_to root_url, :notice => 'Activation e-mail sent!'
    else
      render 'new'
    end
  end

  def recipes
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
      return
    end
    names = name_to_use(@user)
    @name = names[0]
    @first = names[1]
    @recipes = @user.recipes
    @avatarUrl = get_avatar_url(@user)
    @createdRecipes = @user.recipes.where(:created_by => @user.id)
    @totalPages = (@createdRecipes.count / 8.0).ceil
    @createdRecipes = @createdRecipes.order('created_at DESC').page(params[:page]).per(8)
    respond_to do |format|
      format.html
      format.js { 
        @page = params[:page].to_i
        @totalPages = @totalPages
      }
      format.json {render :partial => 'users/show.json'}
    end
  end

  def faved_recipes
    begin
      @user = User.includes(:personalRecipeInfo, :recipes => [:ingredients]).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url
      return
    end
    names = name_to_use(@user)
    @name = names[0]
    @first = names[1]

    @favedRecipes = get_faves(@user).page(params[:page]).per(9).order('created_at DESC')
    respond_to do |format|
      format.html {render :layout => 'wall'}
      format.json {render :json => @favedRecipes}
    end
  end

  def invite
    if current_user
      auth = current_user.authorizations.select{|auth| auth.provider == 'facebook'}.first
      if auth or auth.empty?
        uri = URI.parse("https://graph.facebook.com/#{auth.uid}/friends?fields=installed,name&access_token=#{auth.access_token}")
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        #http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        data = Net::HTTP::Get.new(uri.request_uri)
        @friends = JSON.parse(http.request(data).body)['data']
        @friends = @friends.sort_by{|hsh| hsh['name']}
      end
    end
    render :layout => 'wall'
  end

  def favorite
    user = current_user
    recipe = Recipe.find_by_url_slug(params[:recipe_id])
    info = user.personalRecipeInfo.find_by_recipe_id(recipe.id)
    if info
      if info['favorite'] == false
        recipe['favorites'] += 1
        info['favorite'] = true
      else
        recipe['favorites'] -= 1
        info['favorite'] = false
      end
    else
      user.recipes << recipe
    end
    if info.save && recipe.save
      render :json => recipe
    else
      render :json => recipe
    end
  end

  private

  def get_faves(user)
    user.recipes.where("personal_recipe_infos.favorite IS TRUE")
  end

  def get_avatar_url(user)
    authorization = Authorization.find_by_user_id_and_provider(user.id, 'facebook')
    if authorization
      return "http://graph.facebook.com/#{authorization.uid}/picture"
    else
      digestHash = Digest::MD5.hexdigest(user.email.downcase)
      return "http://www.gravatar.com/avatar/#{digestHash}?s=50"
    end
  end

  def is_logged_in?
    if current_user
      redirect_to root_url, :notice => "You're already logged in!"
    end
  end

  def name_to_use(user)
    if user.display_name
      return [user.display_name, user.display_name.split(' ')[0]]
    elsif user.name
      return [user.name, user.name.split(' ')[0]]
    else
      return [user.email, user.email]
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_page.html.haml
%div.left_page.user_edit_page
  %h1 Edit your profile
  = form_for @user do |f|
    = f.label :display_name, 'Display Name: '
    = f.text_field :display_name
    %br/
    = f.submit 'Update', :class => 'pretty_button inline'
%div.right_page.user_edit_page
  - if !@passwordChange
    %h1 Change your password
    = form_for @user, :url => update_password_user_url, :method => :post do |f|
      = label_tag 'old_password', 'Old Password: '
      = password_field_tag 'old_password'
      %br
      = f.label :password, 'New Password: '
      = f.password_field :password
      %br
      = f.label :password_confirmation, 'Confirm New Password: '
      = f.password_field :password_confirmation
      %br
      = f.submit 'Update password', :class => 'pretty_button inline'
  - if !!current_user.is_activated?
    %h1 Activate your account
    = form_for @user, :url => generate_activate_user_url, :method => :post do |f|
      = f.label :email
      = f.text_field :email
      %br
      = f.submit 'Send Activation E-mail', :class => 'pretty_button inline'

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    %div.errors
      %h2 Form is invalid
      %ul
      - @user.errors.full_messages.each do |message|
        %li
          = message
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :email
    %br/
    = f.text_field :email
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %p.button
    = f.submit 

app/views/users/_show.json.erb
{
  "name"  : "<%= @user.name %>",
  "id"    : "<%= @user.id %>",
  "joined" : "<%= @user.created_at %>",
  "recipes" :
    {
      <% @createdRecipes.each_with_index do |recipe, index| %>
        "<%= index %>" :
        {
          "name"  : "<%= recipe.name%>"
        }
      <% end %>

    },
  "ratings" :
    {
      <% @ratedRecipes.each_with_index do |recipe, index| %>
        "<%= index %>" :
        {
          "name"  : "<%= recipe.name %>"
        }
      <% end %>
    }
}

app/views/users/edit.html.haml
= render 'edit_page'

app/views/users/faved_recipes.html.haml
= content_for :include_javascripts do
  = javascript_include_tag 'infinite_recipes'
%div
  %h1
    = "#{@name}'s Forked Recipes"
  = render :partial => 'recipes/recipes_overlay', :locals => {:recipes => @favedRecipes, :type => 'faved'}

app/views/users/index.html.haml
%div.inner.left_page.index_page
  - if current_user
    %h2.welcome
      = "Welcome back, #{@firstName}!"
    - if current_user.is_activated?
      = link_to 'New Recipe', new_recipe_path, :class => 'pretty_button add'
    - else
      %p
        To create a new recipe  
        = link_to 'activate your profile.', edit_user_path(current_user)    
    %p      
      = link_to 'Browse Recipes', recipes_path, :class => 'pretty_button'
    = form_tag("../search/recipes", :method => 'get', :class => 'home_page_search') do
      = text_field_tag :q, nil, {:placeholder => 'Search recipes!'}
      = submit_tag 'Search', :class => 'pretty_button inline small_font'

%div.inner.right_page.index_page
  - if current_user
    - if @recentlyViewed
      %h2 Your Recent History
      = render :partial => 'recipes/recipes', :locals => {:recipes => @recentlyViewed, :type => 'index'}
    - else
      %h2
        No recipes viewed in a while!
  - else
    %h1 Howdy, Stranger!
    %p You need to login or sign up start your recipe book!
    = render :partial => 'recipes/recipes', :locals => {:recipes => @newestRecipes, :type => 'index'}

app/views/users/invite.html.haml
%h1{:style => 'display: inline-block;'} Friends:
%div.right
  %a.pretty_button.inline{:href => '#'}
    Invite
%div.friend_wrap
  - @friends.each do |friend|
    %div.friend-box
      = image_tag "http://graph.facebook.com/#{friend['id']}/picture", :alt => friend['name']
      %p
        = friend['name']
  %div.clearfix

app/views/users/new.html.haml
%div.left_page.align_top
  %h1 Connect with Facebook...
  %div.facebook_login
    %p
      Connect with your Facebook account to share recipes with your friends!
    = link_to (image_tag 'facebook-login.png'), '/auth/facebook'
%div.right_page
  %h1 or register normally!
  = render 'form'

app/views/users/recipes.html.haml
%div.recipe_book_header
  = image_tag @avatarUrl
  %h1
    = @name + '\'s Recipe Book'
%div.left_page
  - if @createdRecipes
    - if @createdRecipes.count > 4
      = render :partial => 'recipes/recipes', :locals => {:recipes => @createdRecipes[0..3], :type => 'created'}
    - else
      = render :partial => 'recipes/recipes', :locals => {:recipes => @createdRecipes[0..@createdRecipes.count], :type => 'created'}
%div.right_page
  - if @createdRecipes.count > 4
    = render :partial => 'recipes/recipes', :locals => {:recipes => @createdRecipes[4..@createdRecipes.count], :type => 'rated'}
  %p
    :plain
      More recipes &rarr;
%div.recipe_book_page_turn.forward
  %a{:href=>'#'}turn
%div.recipe_book_page_turn.backward
  %a{:href=>'#'}turn

app/views/users/recipes.js.erb
<% if @page > 0 %>
  <% if @page == 1 %>
    $('.recipe_book_page_turn.backward').hide()
    $('.recipe_book_page_turn.forward').show()
    $('div.wrap').addClass('page').removeClass('page_left page_both')
  <% elsif @page < @totalPages %>
    $('.recipe_book_page_turn.forward').show()
    $('.recipe_book_page_turn.backward').show()
    $('div.wrap').addClass('page_both').removeClass('page page_left')
  <% elsif @page == @totalPages %>
    $('.recipe_book_page_turn.forward').hide()
    $('.recipe_book_page_turn.backward').show()
    $('div.wrap').addClass('page_left').removeClass('page page_both')
  <% end %>

  <% if @createdRecipes.count > 4 %>
    $('.left_page').empty().append("<%= escape_javascript(render :partial => 'recipes/recipes', :locals => {:recipes => @createdRecipes[0..3], :type => 'created'}) %>")
    $('.right_page').empty().append("<%= escape_javascript(render :partial => 'recipes/recipes', :locals => {:recipes => @createdRecipes[4..@createdRecipes.count], :type => 'created'}) %>")
  <% elsif @createdRecipes.count <= 4 %>
    $('.left_page').empty().append("<%= escape_javascript(render :partial => 'recipes/recipes', :locals => {:recipes => @createdRecipes[0..@createdRecipes.count], :type => 'created'}) %>")
    $('.right_page').empty()
  <% end %>
<% end %>

app/views/users/show.html.haml
- content_for :add_javascripts do
  = javascript_include_tag 'raphael-min'
  = javascript_include_tag 'graphs'
%div.left_page.user_page
  %div.user_page_header
    %h1
      = image_tag @avatarUrl
      = "#{@name}"
    - if @user == current_user
      = link_to 'Edit Profile', edit_user_path(@user), :class => 'pretty_button inline small_font edit'
  %div.user_stats
    %div.counts
      %p
        = link_to (faved_recipes_user_url(@user)) do
          %strong
            = @totalFav
          forked 
      %p
        = link_to (recipes_user_url(@user)) do
          %strong
            = @totalCreated
          created
      %div.clearfix
    %div.clearfix
  %div.recents
    - if @recentCreated
      %div.recent
        = render :partial => 'recipes/recipe', :locals => {:recipe => @recentCreated, :type => 'created'}
        %h2 Recently Created
    - if @recentFav
      %div.recent
        = render :partial => 'recipes/recipe', :locals => {:recipe => @recentFav, :type => 'rated'}
        %h2 Recently Forked
    %div.clearfix
%div.right_page.user_page
  - if @allIngredients
    %div.top_ingredients
      %h2
        = "Most Used Ingredients"
      %div#ingredients_graph
%script
  - if @allIngredients
    != "generatePieGraph(#{@allIngredients.to_json})"