config/routes.rb
Recipes::Application.routes.draw do
  get "password_resets/new"

  root :to => 'users#index'
  get "sessions/new"
  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  match '/auth/:provider/callback', :to => 'sessions#omni'
  match '/auth/failure', :to => 'sessions#failure'
  post '/users/activate' => 'users#activate'
  resources :password_resets, :only => [:new, :edit, :update, :create]
  resources :users do
    member do
      get 'recipes'
      get 'faved_recipes'
      post 'update_password'
      match '/:activation_id/activate' => 'users#new_user_activate', :as => 'activate'
      post '/generate_activation' => 'users#profile_activate', :as => 'generate_activate'
    end
    resources :recipes do
      match '/fav' => 'users#favorite'
    end
  end
  resources :sessions
  resources :ingredients do
    member do
      get 'recipes'
    end
  end
  
  resources :recipes do
    match '/fav' => 'recipes#favorite'
  end

  scope '/search' do
    match '/' => 'search#index'
    match '/recipes' => 'search#recipes'
  end

  scope '/recipes' do
    match '/:name' => 'recipes#show'
    match '/:id/update_rating', :controller => 'recipes', :action => 'update_rating'
    match '/new/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
    match '/:id/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
  end

  scope '/user' do
    match '/' => 'users#me'
    match '/invite' => 'users#invite'
  end
  #match '/recipes/:name', :controller => 'recipes', :action => 'show'
  match '/ingredients/:name' => 'ingredients#show'
  
  #match '/:email', :controller => 'users', :action => 'edit'
  match '/me' => 'users#me'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :amounts
  has_many :recipes, :through => :amounts
  acts_as_indexed :fields => [:name]

  validates_presence_of :name, :on => :create
  validates_presence_of :url_slug, :on => :create  

  def to_param
    url_slug
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  layout 'recipes'
  helper_method :sort_type, :sort_direction
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.order(sort_type + " " + sort_direction)
    @activeSort = sort_type
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find_by_url_slug(params[:id])
    @ingredient = Ingredient.find(params[:id]) if @ingredient.nil?
    @recipes = @ingredient.recipes.order('created_at DESC')
    logger.debug @recipes.inspect
    respond_to do |format|
      format.html {render :layout => 'wall'}
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end

  def recipes
    @ingredient = Ingredient.find(params[:id])
    @recipes = @ingredient.recipes
  end
end

def sort_type
  Recipe.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
end

def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.haml
= form_for(@ingredient) do |f|
  = if @ingredient.errors.any?
    %div#error_explaination
      %h2= pluralize(@ingredient.errors.count, 'error') 
      %ul
        = @ingredient.errors.full_message.each do |msg|
          %li= msg
  %div.field
    = f.label :name
    %br/
    = f.text_field :name
  %div.actions
    = f.submit

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.name %></td>
    <td><%= link_to 'Show', ingredient %></td>
  </tr>
<% end %>
</table>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/recipes.html.haml
%h2
  Recipes using  
  = @ingredient.name
%div
  - @recipes.each do |recipe|
    %div
      %p
        = link_to recipe.name, recipe

app/views/ingredients/show.html.haml
%div.ingredient_show_header.show_header
  %div.left
    %h1
      = @ingredient.name
  %div.right
    %div.sorter
      = sortable 'name'
      = sortable 'created_at', 'Date'
      = sortable 'favorites', 'Forks'
  %div.clearfix
  %h3
    Featured in 
    = pluralize(@recipes.length, 'recipe')
= render :partial => 'recipes/recipes_overlay', :locals => {:recipes => @recipes, :type => 'ingredient'}