config/routes.rb
Recipes::Application.routes.draw do
  get "password_resets/new"

  root :to => 'users#index'
  get "sessions/new"
  get "users/new"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  match '/auth/:provider/callback', :to => 'sessions#omni'
  match '/auth/failure', :to => 'sessions#failure'
  post '/users/activate' => 'users#activate'
  resources :password_resets, :only => [:new, :edit, :update, :create]
  resources :users do
    member do
      get 'recipes'
      get 'faved_recipes'
      post 'update_password'
      match '/:activation_id/activate' => 'users#new_user_activate', :as => 'activate'
      post '/generate_activation' => 'users#profile_activate', :as => 'generate_activate'
    end
    resources :recipes do
      match '/fav' => 'users#favorite'
    end
  end
  resources :sessions
  resources :ingredients do
    member do
      get 'recipes'
    end
  end
  
  resources :recipes do
    match '/fav' => 'recipes#favorite'
  end

  scope '/search' do
    match '/' => 'search#index'
    match '/recipes' => 'search#recipes'
  end

  scope '/recipes' do
    match '/:name' => 'recipes#show'
    match '/:id/update_rating', :controller => 'recipes', :action => 'update_rating'
    match '/new/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
    match '/:id/render_ingredients_input', :controller => 'recipes', :action => 'render_ingredients_input'
  end

  scope '/user' do
    match '/' => 'users#me'
    match '/invite' => 'users#invite'
  end
  #match '/recipes/:name', :controller => 'recipes', :action => 'show'
  match '/ingredients/:name' => 'ingredients#show'
  
  #match '/:email', :controller => 'users', :action => 'edit'
  match '/me' => 'users#me'
end

app/views/layouts/_footer.html.haml
%div.footer
  %div.left
    %ul
      %li
        = link_to 'Home', root_url
      %li
        = link_to 'Search', '/search'
      %li
        = link_to 'Browse', recipes_url
  %div.right
    copyright blah blah
  %div.clearfix

app/views/layouts/_status_bar.html.haml
- if flash['flashes']
  %div.flashes
    - flash.each do |name, msg|
      %div.flash{:id => "flash_#{name}"}
        = msg
%div#status_bar
  %div.left
    = link_to 'Home', root_url
  %div.right
    - if current_user
      = link_to "Log Out", log_out_path
      = link_to "Invite", invite_path
      = link_to "Profile", current_user 
    - else
      %span
        = link_to 'Login', log_in_path, :remote => true
  %div.clearfix

app/views/layouts/application.html.haml
!!! html5
%head
  = stylesheet_link_tag 'application'
  = javascript_include_tag 'application'
  = csrf_meta_tag
%body
  = render 'layouts/status_bar'
  = yield

app/views/layouts/recipes.html.haml
!!! html5
%head
  = stylesheet_link_tag 'application'
  = javascript_include_tag 'application'
  = yield :add_javascripts
  = csrf_meta_tag
%body
  = render 'layouts/status_bar'
  = yield :before_wrap_content
  - if @page == false or @page.nil?
    %div.wrap.no_page
      = yield
  - elsif @page == 'left'
    %div.wrap.page_left
      = yield
  - else
    %div.wrap.page
      = yield
  = render 'layouts/footer'

app/views/layouts/users.html.haml
!!! html5
%head
  = stylesheet_link_tag 'application'
  = javascript_include_tag 'application'
  = yield :add_javascripts
  = csrf_meta_tag
%body
  = render 'layouts/status_bar'
  = yield :content_before_wrap
  - if @page == true or @page.nil?
    %div.wrap.page
      = yield
  - elsif @page == 'left'
    %div.wrap.page_left
      = yield
  - elsif @page == 'both'
    %div.wrap.page_both
      = yield
  - else
    %div.wrap.no_page
      = yield
  = render 'layouts/footer'

app/views/layouts/wall.html.haml
!!! html5
%head
  = stylesheet_link_tag 'application'
  = javascript_include_tag 'application'
  = yield :add_javascripts
  = csrf_meta_tag
%body
  = render 'layouts/status_bar'
  = yield :before_wrap_content
  %div.wall_wrap
    = yield
  = render 'layouts/footer'